### ISSUE TITLE
New devices listening to port 10000

### ISSUE THREAD

**Issue by mhilcher** [loki29pl/homebridge-weconn#2]
There are new devices listening on port 10000.
I did not find a fork button to do some changes and send a pull request, but maybe you can change it, if you like. 

Change in the config (port optional):

   "accessories": [
        {
            "accessory": "WeConn",
            "name": "Plug name",
            "ip_address": "192.168.1.3",
            "mac": "adbd11235611", 
            "port": 10000
        }
    ]

Changes in index.js (set port):

        if (!config.mac) {
            throw new Error('Error in WeConn accessory. Missing MAC');
        }

        if (!config.port) {
            this.port = 9957;
        }
        else {
            this.port = config.port;
       } 

... 

      client.connect(this.port, this.config.ip_address, () => {

Still have to find out if the new devices work with this change, but it could be an improvement for upcoming weconn devices. 

Martin

**Comment by loki29pl** [comment]
@mhilcher Thanks for your input. Please download new version and test. Please give me feedback after yours test. 

Michał

**Comment by mhilcher** [comment]
Hi @loki29pl,
thank you for your fast support.
It seems, that not just the port changed but also the commands. I tried to find out with wireshark, but couldn't find the correct sequence.
But I appreciate your work and hope that this change can be an improvement in the future.

Martin
